## ---- echo=FALSE---------------------------------------------------------
knitr::opts_chunk$set(comment = NA, message = FALSE, warning = FALSE, width = 100)
knitr::opts_chunk$set(fig.align = "center", fig.height = 4, fig.width = 6)
knitr::opts_chunk$set(echo = TRUE)
#knitr::opts_chunk$set(cache = TRUE, autodep=TRUE)  #$
knitr::opts_chunk$set(cache = FALSE) #, autodep=TRUE)  #$

## ---- eval=FALSE---------------------------------------------------------
## install.packages("./Analysis/Code/CastorR_0.1.00.tar.gz", repos = NULL, type="source")

## ------------------------------------------------------------------------
library(CastorR)
dat <- castor_format_R(fn = "CRF_export_2.xlsx")
str(dat)

## ---- eval=FALSE, echo=FALSE---------------------------------------------
## ## Print codebook generated by the data
## ggplot2::theme_set(ggplot2::theme_bw())
## pander::panderOptions("table.split.table", Inf)
## library(codebook)
## codebook(dat$`Study results`)

